import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';
import listIcon from '@/app/assets/list-icon.png';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const iconSize = 36;
const bg = 'bg-slate-800';
const matter = 'bg-slate-600';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${bg}`}>
        <body className={inter.className}>
          <SignedOut>
            <section className={`${bg}`}>
              <SignInButton>Sign</SignInButton>
            </section>
          </SignedOut>
          <SignedIn>
            <section className={`fixed top-0 left-0 w-full  ${matter}`}>
              <div className="flex justify-between align-baseline h-16 p-5">
                <UserButton />
                Settings
              </div>
            </section>
            <section className={`${bg}`}>{children}</section>
            <nav className={`fixed bottom-0 left-0 w-full ${matter}`}>
              <ul className="flex justify-around p-3">
                <li>
                  <Link href="/">
                    <Image src={listIcon} alt="List Icon" width={iconSize} height={iconSize} />
                  </Link>
                </li>
              </ul>
            </nav>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
